export enum CustomErrorCode {
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  UNPROCESSABLE = 'UNPROCESSABLE_ENTITY',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  MISSING_ADDITIONAL_DATA = 'MISSING_ADDITIONAL_DATA',
}
